import { Link } from "@tanstack/react-router";
import { Heart, Menu, Search, ShoppingBag, X, Minus, Plus, ArrowRight } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { products, formatPrice, categoryNames, type Product } from "@/lib/catalog";
import { useStore } from "@/lib/store";

const nav=[{to:"/shop",label:"Shop All"},{to:"/thakur-sewa",label:"Thakur Sewa"},{to:"/men",label:"Men"},{to:"/women",label:"Women"},{to:"/about",label:"Our Story"},{to:"/contact",label:"Contact"}] as const;

export function Header(){ const {count,setCartOpen}=useStore(); const [scrolled,setScrolled]=useState(false); const [search,setSearch]=useState(false); const [query,setQuery]=useState("");
 useEffect(()=>{const fn=()=>setScrolled(scrollY>30); addEventListener("scroll",fn); return()=>removeEventListener("scroll",fn)},[]);
 const results=query.length>1?products.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())).slice(0,4):[];
 return <><div className="bg-primary px-4 py-2 text-center text-[11px] font-semibold uppercase tracking-[.2em] text-primary-foreground">Complimentary shipping across India on orders over ₹1,499</div>
 <header className={`sticky top-0 z-40 border-b border-border/70 bg-background/95 backdrop-blur-xl transition-all ${scrolled?"py-2 shadow-sm":"py-4"}`}><div className="mx-auto grid max-w-7xl grid-cols-[auto_1fr_auto] items-center gap-3 px-4 lg:px-8">
 <Sheet><SheetTrigger asChild><Button variant="ghost" size="icon" className="lg:hidden" aria-label="Open menu"><Menu/></Button></SheetTrigger><SheetContent side="left" className="w-[88%] bg-background"><SheetHeader><SheetTitle className="font-display text-3xl text-primary">Itrkunj</SheetTitle><SheetDescription>Fragrance rooted in tradition.</SheetDescription></SheetHeader><nav className="mt-10 flex flex-col gap-5">{nav.map(n=><Link key={n.to} to={n.to} className="border-b border-border pb-4 font-display text-2xl">{n.label}</Link>)}</nav></SheetContent></Sheet>
 <Link to="/" className="justify-self-center text-center lg:justify-self-start"><span className="block font-display text-3xl font-semibold leading-none text-primary">Itrkunj</span><span className="mt-1 block text-[9px] uppercase tracking-[.34em] text-muted-foreground">Pure Attars · Kannauj</span></Link>
 <nav className="hidden justify-self-center lg:flex gap-6 xl:gap-8">{nav.map(n=><Link key={n.to} to={n.to} activeProps={{className:"text-primary"}} className="story-link text-xs font-semibold uppercase tracking-[.12em] text-foreground/75">{n.label}</Link>)}</nav>
 <div className="flex justify-self-end"><Button variant="ghost" size="icon" aria-label="Search" onClick={()=>setSearch(!search)}><Search/></Button><Button variant="ghost" size="icon" aria-label="Wishlist" asChild><Link to="/shop" search={{wishlist:true}}><Heart/></Link></Button><Button variant="ghost" size="icon" aria-label={`Shopping bag with ${count} items`} className="relative" onClick={()=>setCartOpen(true)}><ShoppingBag/><span className="absolute right-0 top-0 grid h-4 min-w-4 place-items-center rounded-full bg-gold px-1 text-[9px] text-gold-foreground">{count}</span></Button></div>
 </div>{search&&<div className="absolute inset-x-0 top-full border-b bg-background p-4 shadow-lg animate-fade-in"><div className="mx-auto max-w-2xl relative"><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search sandalwood, rose, oud…" className="h-12 w-full border-b border-primary bg-transparent px-10 outline-none"/><Search className="absolute left-2 top-3.5 size-5 text-muted-foreground"/><button onClick={()=>setSearch(false)} className="absolute right-2 top-3.5" aria-label="Close search"><X className="size-5"/></button>{results.length>0&&<div className="pt-3">{results.map(p=><Link key={p.id} to="/product/$slug" params={{slug:p.slug}} onClick={()=>setSearch(false)} className="flex items-center justify-between py-2 text-sm"><span>{p.name} <span className="text-muted-foreground">— {p.subtitle}</span></span><span>{formatPrice(p.price)}</span></Link>)}</div>}</div></div>}</header></> }

export function CartDrawer(){const {cart,cartOpen,setCartOpen,change,subtotal}=useStore(); return <Sheet open={cartOpen} onOpenChange={setCartOpen}><SheetContent className="flex w-full flex-col bg-background sm:max-w-md"><SheetHeader><SheetTitle className="font-display text-3xl">Your bag</SheetTitle><SheetDescription>{cart.length?"Small-batch attars, reserved for you.":"Your fragrance journey starts here."}</SheetDescription></SheetHeader><div className="mt-6 flex-1 space-y-5 overflow-auto">{cart.map(i=>{const p=products.find(x=>x.id===i.id); if(!p)return null; return <div key={`${i.id}-${i.size}`} className="grid grid-cols-[80px_1fr] gap-4 border-b pb-5"><img src={p.image} alt={p.name} className="h-24 w-20 object-cover"/><div><div className="flex justify-between"><div><p className="font-display text-lg">{p.name}</p><p className="text-xs text-muted-foreground">{i.size} ml</p></div><p className="text-sm font-semibold">{formatPrice(p.price*(i.size/6)*i.quantity)}</p></div><div className="mt-3 inline-flex items-center border"><Button variant="ghost" size="icon" className="h-7 w-7" onClick={()=>change(i.id,i.size,-1)}><Minus/></Button><span className="w-7 text-center text-xs">{i.quantity}</span><Button variant="ghost" size="icon" className="h-7 w-7" onClick={()=>change(i.id,i.size,1)}><Plus/></Button></div></div></div>})}</div><div className="border-t pt-5"><div className="mb-4 flex justify-between font-semibold"><span>Subtotal</span><span>{formatPrice(subtotal)}</span></div><Button size="lg" className="w-full" asChild disabled={!cart.length}><Link to="/checkout" onClick={()=>setCartOpen(false)}>Proceed to checkout <ArrowRight/></Link></Button><p className="mt-3 text-center text-xs text-muted-foreground">Shipping calculated at checkout · Demo orders only</p></div></SheetContent></Sheet>}

export function ProductCard({product}:{product:Product}){const {add,wishlist,toggleWishlist}=useStore(); return <article className="group min-w-0"><div className="relative aspect-[4/5] overflow-hidden bg-muted"><img loading="lazy" src={product.image} alt={`${product.name} attar bottle`} className="h-full w-full object-cover transition duration-700 group-hover:scale-105 group-hover:opacity-0"/><img loading="lazy" src={product.hoverImage} alt="" className="absolute inset-0 h-full w-full object-cover opacity-0 transition duration-700 group-hover:scale-105 group-hover:opacity-100"/>{product.badge&&<span className="absolute left-3 top-3 bg-background/90 px-2 py-1 text-[10px] uppercase tracking-widest">{product.badge}</span>}<Button variant="ivory" size="icon" onClick={()=>toggleWishlist(product.id)} className="absolute right-3 top-3" aria-label="Toggle wishlist"><Heart className={wishlist.includes(product.id)?"fill-primary text-primary":""}/></Button><Button onClick={()=>add(product.id)} className="absolute inset-x-3 bottom-3 translate-y-16 opacity-0 group-hover:translate-y-0 group-hover:opacity-100">Quick add · 6 ml</Button></div><div className="pt-4"><div className="flex justify-between gap-3"><div className="min-w-0"><Link to="/product/$slug" params={{slug:product.slug}} className="font-display text-xl font-semibold hover:text-primary">{product.name}</Link><p className="mt-1 truncate text-xs text-muted-foreground">{product.subtitle}</p></div><p className="shrink-0 text-sm font-semibold">{formatPrice(product.price)}</p></div><p className="mt-2 text-xs text-gold-strong">★ {product.rating} <span className="text-muted-foreground">({product.reviews})</span></p></div></article>}

export function Footer(){return <footer className="bg-ink text-ink-foreground"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-14 md:grid-cols-[1.5fr_1fr_1fr] lg:px-8"><div><p className="font-display text-4xl">Itrkunj</p><p className="mt-4 max-w-sm text-sm text-ink-muted">Alcohol-free attars, distilled with patience and composed for devotion, celebration, and the quiet rituals of every day.</p></div><div><p className="mb-4 text-xs uppercase tracking-widest text-gold">Explore</p><div className="grid gap-2 text-sm">{nav.slice(0,4).map(n=><Link key={n.to} to={n.to}>{n.label}</Link>)}</div></div><div><p className="mb-4 text-xs uppercase tracking-widest text-gold">The house</p><div className="grid gap-2 text-sm"><Link to="/about">Our story</Link><Link to="/contact">Contact</Link><span>Care guide</span><span>Shipping & returns</span></div></div></div><div className="border-t border-ink-line px-4 py-5 text-center text-xs text-ink-muted">© 2026 Itrkunj · Crafted in Kannauj, India</div></footer>}

export function Newsletter(){const [email,setEmail]=useState(""); return <form onSubmit={e=>{e.preventDefault(); if(email.includes("@")){toast.success("Welcome to the Itrkunj circle");setEmail("")}else toast.error("Please enter a valid email")}} className="mx-auto mt-8 flex max-w-lg border-b border-primary"><input value={email} onChange={e=>setEmail(e.target.value)} type="email" required placeholder="Your email address" className="h-12 flex-1 bg-transparent px-2 outline-none"/><Button type="submit" variant="ghost">Join <ArrowRight/></Button></form>}

export function CategoryTitle({category}:{category:Product["category"]}){return <>{categoryNames[category]}</>}